AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false

require:
  - rubocop-performance
  - rubocop-rspec

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*_spec.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Metrics/MethodLength:
  Max: 20

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

Naming/MethodName:
  IgnoredPatterns:
    - toList
    - inVLabel
    - outVLabel
    - inV
    - outV

Naming/VariableName:
  AllowedIdentifiers:
    - inV
    - outV
    - inVLabel
    - outVLabel

Naming/MethodParameterName:
  AllowedNames:
    - id
    - inV
    - outV
    - inVLabel
    - outVLabel

Metrics/ParameterLists:
  Max: 6

Style/WordArray:
  Exclude:
    - spec/**/*_spec.rb